// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorConfig
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidEditorConfigPackageString = "6736c72d-7a27-49f0-9153-413ff47963ef";
        public const string guidEditorConfigPackageCmdSetString = "a21ee3c5-45b9-4bd8-abd7-30ceb3d990c5";
        public static Guid guidEditorConfigPackage = new Guid(guidEditorConfigPackageString);
        public static Guid guidEditorConfigPackageCmdSet = new Guid(guidEditorConfigPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddGroup = 0x0001;
        public const int CreateEditorConfigFileId = 0x0100;
    }
}
