// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorConfig
{
    static class Vsix
    {
        public const string Id = "EditorConfig.Mads Kristensen.1209461d-57f8-46a4-814a-dbe5fecef941";
        public const string Name = "EditorConfig";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
