//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorConfig.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditorConfig.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An .editorconfig file already exist in this location.
        /// </summary>
        internal static string EditorConfigFileAlreadyExist {
            get {
                return ResourceManager.GetString("EditorConfigFileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format document.
        /// </summary>
        internal static string FormatDocument {
            get {
                return ResourceManager.GetString("FormatDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid value for the &quot;{1}&quot; property.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported by Visual Studio.
        /// </summary>
        internal static string NotSupportedByVS {
            get {
                return ResourceManager.GetString("NotSupportedByVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &quot;root&quot; is allowed outside a section..
        /// </summary>
        internal static string ValidateOnlyRootAllowed {
            get {
                return ResourceManager.GetString("ValidateOnlyRootAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &quot;{0}&quot; is unknown..
        /// </summary>
        internal static string ValidateUnknownKeyword {
            get {
                return ResourceManager.GetString("ValidateUnknownKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property is overridden by a property by the same name in this section..
        /// </summary>
        internal static string ValidationDuplicateProperty {
            get {
                return ResourceManager.GetString("ValidationDuplicateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section with the value &quot;{0}&quot; has already been defined..
        /// </summary>
        internal static string ValidationDuplicateSection {
            get {
                return ResourceManager.GetString("ValidationDuplicateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &quot;indent_style&quot; is set to tab, it may be desirable to leave indent_size unspecified so readers may view the file using their preferred indentation width..
        /// </summary>
        internal static string ValidationIndentSizeUnneeded {
            get {
                return ResourceManager.GetString("ValidationIndentSizeUnneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values must not end with a {0}..
        /// </summary>
        internal static string ValidationInvalidEndChar {
            get {
                return ResourceManager.GetString("ValidationInvalidEndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid value for severity..
        /// </summary>
        internal static string ValidationInvalidSeverity {
            get {
                return ResourceManager.GetString("ValidationInvalidSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be specified..
        /// </summary>
        internal static string ValidationMissingPropertyValue {
            get {
                return ResourceManager.GetString("ValidationMissingPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A severity must be specified. Example: true:warning..
        /// </summary>
        internal static string ValidationMissingSeverity {
            get {
                return ResourceManager.GetString("ValidationMissingSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The globbing pattern &quot;{0}&quot; doesn&apos;t match any files. Consider removing the section..
        /// </summary>
        internal static string ValidationNoMatch {
            get {
                return ResourceManager.GetString("ValidationNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is a duplicate of one in
        ///&quot;{0}&quot; and can be safely removed..
        /// </summary>
        internal static string ValidationParentPropertyDuplicate {
            get {
                return ResourceManager.GetString("ValidationParentPropertyDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Root&quot; is only allowed in the beginning of the document..
        /// </summary>
        internal static string ValidationRootInSection {
            get {
                return ResourceManager.GetString("ValidationRootInSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections must be surrounded by &quot;[&quot; and &quot;]&quot;..
        /// </summary>
        internal static string ValidationSectionSyntaxError {
            get {
                return ResourceManager.GetString("ValidationSectionSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; property does not support a severity suffix..
        /// </summary>
        internal static string ValidationSeverityNotApplicable {
            get {
                return ResourceManager.GetString("ValidationSeverityNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces in globbing patterns are allowed, but are often the result of a typo. Make sure the globbing pattern is accurate..
        /// </summary>
        internal static string ValidationSpaceInSection {
            get {
                return ResourceManager.GetString("ValidationSpaceInSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no need to specify &quot;tab_width&quot; unless it differs from the value of &quot;indent_size&quot;..
        /// </summary>
        internal static string ValidationTabWidthUnneeded {
            get {
                return ResourceManager.GetString("ValidationTabWidthUnneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error. Element not valid at current location..
        /// </summary>
        internal static string ValidationUnknownElement {
            get {
                return ResourceManager.GetString("ValidationUnknownElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style &quot;{0}&quot; is unknown. A capitalization style must always be specified..
        /// </summary>
        internal static string ValidationUnknownStyle {
            get {
                return ResourceManager.GetString("ValidationUnknownStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style &quot;{0}&quot; is never used. Consider removing it..
        /// </summary>
        internal static string ValidationUnusedStyle {
            get {
                return ResourceManager.GetString("ValidationUnusedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any standard property, a value of &quot;unset&quot; is to remove the effect of that property, even if it has been set before..
        /// </summary>
        internal static string ValueUnset {
            get {
                return ResourceManager.GetString("ValueUnset", resourceCulture);
            }
        }
    }
}
