//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorConfig.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditorConfig.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An .editorconfig file already exist in this location.
        /// </summary>
        internal static string EditorConfigFileAlreadyExist {
            get {
                return ResourceManager.GetString("EditorConfigFileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format document.
        /// </summary>
        internal static string FormatDocument {
            get {
                return ResourceManager.GetString("FormatDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid value for the &quot;{1}&quot; property&quot;.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported by Visual Studio.
        /// </summary>
        internal static string NotSupportedByVS {
            get {
                return ResourceManager.GetString("NotSupportedByVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &quot;{0}&quot; is unknown.
        /// </summary>
        internal static string ValidateUnknownKeyword {
            get {
                return ResourceManager.GetString("ValidateUnknownKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property has already been defined in this section.
        /// </summary>
        internal static string ValidationDuplicateProperty {
            get {
                return ResourceManager.GetString("ValidationDuplicateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section with the value &quot;{0}&quot; has already been defined.
        /// </summary>
        internal static string ValidationDuplicateSection {
            get {
                return ResourceManager.GetString("ValidationDuplicateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values must not end with a {0}.
        /// </summary>
        internal static string ValidationInvalidEndChar {
            get {
                return ResourceManager.GetString("ValidationInvalidEndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid value for severity.
        /// </summary>
        internal static string ValidationInvalidSeverity {
            get {
                return ResourceManager.GetString("ValidationInvalidSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be specified.
        /// </summary>
        internal static string ValidationMissingPropertyValue {
            get {
                return ResourceManager.GetString("ValidationMissingPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A severity must be specified. Example: true:warning.
        /// </summary>
        internal static string ValidationMissingSeverity {
            get {
                return ResourceManager.GetString("ValidationMissingSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property with the same value is defined in parent document
        ///{0}.
        /// </summary>
        internal static string ValidationParentPropertyDuplicate {
            get {
                return ResourceManager.GetString("ValidationParentPropertyDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Root&quot; is only allowed in the beginning of the document.
        /// </summary>
        internal static string ValidationRootInSection {
            get {
                return ResourceManager.GetString("ValidationRootInSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; property does not support a severity suffix.
        /// </summary>
        internal static string ValidationSeverityNotApplicable {
            get {
                return ResourceManager.GetString("ValidationSeverityNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error. Element not valid at current location.
        /// </summary>
        internal static string ValidationUnknownElement {
            get {
                return ResourceManager.GetString("ValidationUnknownElement", resourceCulture);
            }
        }
    }
}
