image: Visual Studio 2017

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test:
  categories:
    except:
      - MEF

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
