// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorConfig
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidEditorConfigPackageString = "6736c72d-7a27-49f0-9153-413ff47963ef";
        public const string guidEditorFactoryString = "13cabf99-9eae-4ecc-a6f4-89f3ad54dc83";
        public const string guidEditorConfigPackageCmdSetString = "13cabf99-9eae-4ecc-a6f4-89f3ad54dc83";
        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public const string iconsString = "666770e6-562f-46d7-a555-3a0cdffe94d2";
        public static Guid guidEditorConfigPackage = new Guid(guidEditorConfigPackageString);
        public static Guid guidEditorFactory = new Guid(guidEditorFactoryString);
        public static Guid guidEditorConfigPackageCmdSet = new Guid(guidEditorConfigPackageCmdSetString);
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);
        public static Guid icons = new Guid(iconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddGroup = 0x0001;
        public const int AddGroupAnyCode = 0x0002;
        public const int EditorContextMenu = 0x0003;
        public const int ErrorListGroup = 0x0004;
        public const int CreateEditorConfigFileId = 0x0100;
        public const int CreateEditorConfigFileAnyCodeId = 0x0200;
        public const int OpenSettingsId = 0x0300;
        public const int NavigateToParentId = 0x0400;
        public const int SuppressErrorId = 0x0500;
        public const int idmAddNew = 0x2200;
        public const int logo = 0x0001;
    }
}
