// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.189
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorConfig
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidEditorConfigPackageString = "6736c72d-7a27-49f0-9153-413ff47963ef";
        public const string guidEditorConfigPackageCmdSetString = "a21ee3c5-45b9-4bd8-abd7-30ceb3d990c5";
        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidEditorConfigPackage = new Guid(guidEditorConfigPackageString);
        public static Guid guidEditorConfigPackageCmdSet = new Guid(guidEditorConfigPackageCmdSetString);
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddGroup = 0x0001;
        public const int AddGroupAnyCode = 0x0002;
        public const int CreateEditorConfigFileId = 0x0100;
        public const int CreateEditorConfigFileAnyCodeId = 0x0200;
        public const int idmAddNew = 0x2200;
    }
}
