// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorConfig
{
    internal sealed partial class Vsix
    {
        public const string Id = "1209461d-57f8-46a4-814a-dbe5fecef941";
        public const string Name = "EditorConfig Language Service";
        public const string Description = @"Language service for .editorconfig files with IntelliSense, validation and more. Supports .NET specific rules and severities";
        public const string Language = "en-US";
        public const string Version = "1.18";
        public const string Author = "Mads Kristensen";
        public const string Tags = "editorconfig";
        public const bool IsPreview = false;
    }
}
